enum Resource {
  SESSIONS = '/sessions',
  SUBSCRIPTIONS = '/subscriptions',
  ACTIONS = '/actions',
  CHANNELS = '/channels',
  SUPPLIERS = '/suppliers',
  ORDERS = '/orders',
  ORDERS_ACTIVITY = '/orders/activities',
  PRODUCTS = '/products',
  VARIANTS = '/variants',
  VENDORS = '/vendors',
  SKUS = '/skus',
  UPCS = '/upcs',
  TAGS = '/tags',
  BUSINESSES = '/businesses',
  ANALYTICS = '/analytics',
  FILTERS = '/filters',
  BUSINESS_MEMBER_VERIFICATIONS = '/businessmemberverifications',
  USERS = '/users',
  INVENTORIES = '/inventories',
  LOCATIONS = '/locations',
  STEPS = '/steps',
  API_ACCOUNTS = '/apiaccounts',
  PLAYS = '/plays',
  RECIPES = '/recipes',
  SCHEDULES = '/schedules'
}

export default Resource;
